#!/bin/bash

	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis
	./harmonicMetropolis

	
