#!/bin/bash
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 

time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis 
time ./harmonicMetropolis

